#!/bin/sh

# Set Wallpaper
pkill hsetroot
#hsetroot -solid "#fbf1c7" &
hsetroot -cover $HOME/pictures/wall.jpg &

# Launch things
#$HOME/.config/picom/launch.sh &
#$HOME/.config/sxhkd/launch.sh &
$HOME/.config/lemonbar/launch.sh &
#$HOME/.config/polybar/launch.sh &

# Dunst
pkill dunst
dunst &

# Cursor
xsetroot -cursor_name left_ptr &